server:
  port: 0

# id приложения - желательно указывать всегда в микросервисных приложениях
spring:
  application:
    name: eclient2

eureka:
  client:
    # url, куда будет происходить регистрация микросервисов
    service-url:
      defaultZone: http://localhost:8761/eureka

# отключение лишних логов, т.к. тут не будем создавать и вызывать микросервисы
logging:
  pattern:
    console: "%C{1.} [%-5level] %d{yyyy-MM-dd HH:mm:ss} - %msg%n"