server:
  port: 8082

# id приложения - желательно указывать всегда в микросервисных приложениях
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # для корректной работы api-gateway
          lower-case-service-id: true


eureka:
  client:
    # url, куда будет происходить регистрация микросервисов
    service-url:
      defaultZone: http://localhost:8081/eureka

# отключение лишних логов, т.к. тут не будем создавать и вызывать микросервисы
logging:
  pattern:
    console: "%C{1.} [%-5level] %d{yyyy-MM-dd HH:mm:ss} - %msg%n"